FROM node:12-alpine

WORKDIR /app

COPY . /app
COPY .env.production .env

RUN set -x \
  && npm install \
  && npm run build

FROM node:12-alpine

WORKDIR /app

COPY --from=0 /app/dist /app/dist
COPY --from=0 /app/package.json /app
COPY --from=0 /app/package-lock.json /app
COPY --from=0 /app/.env /app/

RUN set -x \
  && npm install --production


CMD ["npm", "start"]